# Generated by Django 6.0.6 on 2026-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=3, max_digits=6)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='routing_fue_lat_2a0979_idx'), models.Index(fields=['state', 'retail_price'], name='routing_fue_state_51895b_idx')],
            },
        ),
    ]
