# Generated by Django 5.2.15 on 2026-06-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelstation',
            name='routing_fue_lat_2a0979_idx',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='lon',
        ),
    ]
